name: amp-docker
services:
  amp-docker:
    container_name: amp-docker
    environment:
      - AMP_LICENCE=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - PASSWORD=password
      - PORT=8080
      - TZ=Asia/Kuala_Lumpur
      - USERNAME=admin
      - PORT=8080
    image: kerklangsi/amp-docker:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /media/SSD/AppData/amp-docker:/home/amp
      - /var/run/docker.sock:/var/run/docker.sock
